- hosts: all
  tasks:
  # - name: Install nessesary package
    # yum: 
     #  name: wget.
     #  state: present
     #  update_cache: yes

#   - name: add grafana gpg key
 #    shell: wget https://dl.grafana.com/oss/release/grafana-6.7.3-1.x86_64.rpm

  # - name: Install grafana
   #  shell: yum install grafana-6.7.3-1.x86_64.rpm
    name: Install nginx rpm from a local file
  yum:
    name: /usr/local/src/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    state: present

   - name: Enable and start grafana service
     service:
       name: grafana-server.service
       enabled: yes
       state: started
