- hosts: all
  tasks: 
      - name: to checkthe no of runnig taks
        shell: >
                  ps -aux | head -5
        register: result

      - name: show result
        debug:
          var: result
